### ISSUE TITLE
issues when starting

### ISSUE THREAD

**Issue by soniacross** [DevTeamVersionControl/CandyCrush#14]
games was a fail and felt like scam cause my screen to close programs and what not

**Comment by DevTeamVersionControl** [comment]
It seems like you have downloaded the game from a scam page who copied ours and is distributing malware. We have reported the game page and tried to leave comments warning people, but they have been deleted. We have issued a DMCA take down request that doesn't seem to have done anything, and are trying to contact Itch customer support. So far we have had no success, but we are trying our best to get this thing taken down. If you have downloaded the game from this page, your computer is infected and I would recommend resetting it as soon as possible. If you want to try our game after this, I would recommend downloading it from the releases on this github page or on [our official itch page](https://devflipstudios.itch.io/sweet-dream).

**Comment by soniacross** [comment]
I see but nothing else has happened with my computer after that no problems

**Comment by DevTeamVersionControl** [comment]
Not all malware is immediately visible to the user. It most likely just quietly steals your login information and adds a backdoor so the malware distributor can access your computer again. I would recommend you download malwarebyte and try a virus scan at least.

**Comment by soniacross** [comment]
Ok

**Comment by soniacross** [comment]
It's clear now
